### ISSUE TITLE
Save WEBP as JPG/PNG - extension is not working for me.

### ISSUE THREAD

**Issue by sher10cat** [haddad-github/chrome-extension-webp#2]
Hi, I'm Crystal Identity. I am reporting the exact same issue as what Neko Kawaii reported. I right-click on the webp image, select the extension version of "Save image as..." but nothing happens. (Sorry, I left a one-star review, but if you can figure out how to fix this, I will amend the review.) Full transparency: I have numerous extensions installed on Chrome, so it's quite possible one or more of them may be conflicting with your extension. But because this has happened to me so many times with different extensions, I'm too exhausted from trouble-shooting every single thing. So I ended up installing a rival extension to save Webp's as Jpg's. (Sorry!)

Your response to Neko's review comment was as follows:
______________________________________________

Thank you for letting me know. However, I'm not able to reproduce the error.

To help me debug the issue you're facing, can you confirm that the following:
1. The extension is on version 1.1 (if you go to "chrome://extensions/" in your address bar, decimal number next to the extension's name)
2. What is your chrome version (if you go to "chrome://version/" in your address bar, first info)

I'm aware that you can't reply to this. You can send me the information to my gmail: rafic.george.haddad@gmail.com or if you have github, create an issue here: https://github.com/haddad-github/chrome-extension-webp/issues
______________________________________________

Here's my own reply regarding this info:

1.  Yes, the extension is on version 1.1. (I just installed it a couple of days ago.)
![ChromeExtension_SaveWEBPasJPG-PNG_1 1](https://github.com/haddad-github/chrome-extension-webp/assets/104786860/4f33073d-2b8b-4b2d-8b82-0e10f57667b3)

2.  Here is my Chrome version:
![GoogleChromeVersion_126 0 6478 127_(OfficialBuild)(64-bit)(Cohort_Stable)](https://github.com/haddad-github/chrome-extension-webp/assets/104786860/014b93bd-6c29-415f-bfc2-c9444fa5999b)

Thank you.

**Comment by haddad-github** [comment]
Hi Crystal,

Thank you for the thorough response and for providing the information needed.

The Chrome Extension version and the Chrome version are correct.

I've tested on 2 freshly installed systems and it worked, so I'm pondering 2 reasons for this issue:
a) Chrome permissions that interfere with the extension's script
b) Chrome Extension conflicts, as you've suggested

I'll ask of you 4 things, if possible:

### 1. Make sure that **Sites can use Javascript** is enabled in your Chrome permissions:

Enter ``chrome://settings/content/javascript`` in your address bar and make sure that the **Sites can use JavaScript** is enabled

![image](https://github.com/haddad-github/chrome-extension-webp/assets/68672661/5aa10038-e11f-4ab7-8218-45da59f1567b)

### 2. Make sure that **Site access** is set to **On all sites**, and if not, try it to see if it fixes it:

Enter ``chrome://extensions/?id=dehibjkjchkomncipegajplehmgpodjn`` in your address bar and try setting **Site access** to **On all sites**

![image](https://github.com/haddad-github/chrome-extension-webp/assets/68672661/820b72e4-197e-46f2-889e-57be4ba8f8b4)

### 3. Can you send me a link to a webp image you aren't able to download?

As a way to test and debug specifically where the issue is happening. Maybe there's specific websites or kinds of URL that cause issues that I haven't accounted for.

Here's an example of a webp image I can download, if you can try it out and let me know if it worked for you: https://download.havecamerawilltravel.com/sample-images/webp/webp-example.webp

### 4. If you're comfortable with it, can you send me the list of extensions you're using?

As a way of seeing which could potentially be causing a conflict. You don't have to do it if you're not comfortable sharing it.

Thank you.

**Comment by sher10cat** [comment]
Thank you for your further questions. Here's my first two answers:

1.  Yes, Javascript is enabled on all sites.

![JavaScriptPermission(SitesCanUse)](https://github.com/haddad-github/chrome-extension-webp/assets/104786860/add6af80-4e84-43f3-8b2e-385745343cd7)

2.  Yes, the extension has site access on all sites.

![ExtensionsSiteAccess(OnAllSites)](https://github.com/haddad-github/chrome-extension-webp/assets/104786860/b86c0e79-c9d9-4a26-9c79-0ff5b47b7b74)

**Comment by sher10cat** [comment]
3.  https://download.havecamerawilltravel.com/sample-images/webp/webp-example.webp

Okay, the extension is actually working for this one! I can download it in png, and jpg.

I tried it with a couple of other webp images. It _does_ work on this one:
https://www.craiyon.com/image/AjfmWIBTR6y6RqcUNMHxzw

But it does _not_ work on this one:
https://openart.ai/community/8YxjrnsvKyIwHkO7f7Fn

**Comment by haddad-github** [comment]
> 3. https://download.havecamerawilltravel.com/sample-images/webp/webp-example.webp
> 
> Okay, the extension is actually working for this one! I can download it in png, and jpg.
> 
> I tried it with a couple of other webp images. It _does_ work on this one: https://www.craiyon.com/image/AjfmWIBTR6y6RqcUNMHxzw
> 
> But it does _not_ work on this one: https://openart.ai/community/8YxjrnsvKyIwHkO7f7Fn

Thank you for your test.

You're correct, in your last link (https://openart.ai/community/8YxjrnsvKyIwHkO7f7Fn), it in fact does not work. It works only if you right-click the image and **Open image in new tab** then save it from there, which means that there's something interfering on the original web-page where the image is embedded.

That's perfect, I'll debug from there to see what might be causing this behavior. Thank you.

**Comment by sher10cat** [comment]
Hi haddad, thank you so much for further studying the issue.

BTW, can I ask you to delete the thing I said about the rival extension? I re-installed it and it is working properly now, so I've now deleted that bit from my comment. I don't want to unfairly malign them in public. Thanks!

**Comment by haddad-github** [comment]
> Hi haddad, thank you so much for further studying the issue.
> 
> BTW, can I ask you to delete the thing I said about the rival extension? I re-installed it and it is working properly now, so I've now deleted that bit from my comment. I don't want to unfairly malign them in public. Thanks!

Sure, no worries.

**Comment by sher10cat** [comment]
Thank you. So, for the moment, it looks like you've figured out what you need to look into and debug. But if you still need to know what other extensions I have installed on Chrome, let me know, and I will post them later.

**Comment by haddad-github** [comment]
> Thank you. So, for the moment, it looks like you've figured out what you need to look into and debug. But if you still need to know what other extensions I have installed on Chrome, let me know, and I will post them later.

It's been fixed and the new version (1.2) of the extension should be published soon.

The issue was related to network security policies. Certain websites implement CORS policies that prevent scripts from accessing resources unless the requests include CORS headers. This was blocking the extension from converting the image directly from the website.

This was the error:
![image](https://github.com/haddad-github/chrome-extension-webp/assets/68672661/0805d73d-2608-496b-a614-e8057e596747)

Now the process was modified to fetch the image with CORS headers first, and then convert it.

Thank you for your help.

**Comment by sher10cat** [comment]
Hey, that's awesome! Thank you for so diligently working on the issue. I already upgraded the 1-Star review to 3 Stars. Once the new update is implemented, I will test it again. If it works for all the webp images I try it on, I can upgrade to 5 Stars. 😺

**Comment by sher10cat** [comment]
Oh - would you mind leaving a new comment here when the new update is published, so that I know to check it? Thanks!

**Comment by haddad-github** [comment]
> Oh - would you mind leaving a new comment here when the new update is published, so that I know to check it? Thanks!

Thank you. It's published now. It should be version 1.2 now.

You can go to ``chrome://extensions/`` in your address bar and click **Update** in the upper left, if it hasn't done it on its own.
